/**
 * EmptyExplanation - Empty state for explainability drawer
 */

import { FileQuestion } from 'lucide-react'
import { EmptyState } from '@/components/ui/empty-state'

interface EmptyExplanationProps {
  title?: string
  description?: string
}

/**
 * Display empty state when no explanation is available
 */
export function EmptyExplanation({
  title = 'No Explanation Available',
  description = 'This metric does not have an explanation yet. Explanations are generated by the backend for explainable capabilities.',
}: EmptyExplanationProps) {
  return (
    <EmptyState
      icon={<FileQuestion className="h-8 w-8" />}
      title={title}
      description={description}
    />
  )
}