/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Basic health check endpoint.
         *
         *     Returns 200 OK if the application is running.
         *     This is a lightweight check that doesn't verify database connectivity.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness check endpoint.
         *
         *     Verifies:
         *     - Database is reachable
         *     - Required directories exist
         *     - Essential files are present
         *
         *     Returns 200 OK if all checks pass, 503 otherwise.
         */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Accounts
         * @description Get all accounts with their computed balances.
         */
        get: operations["api_get_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Account Balance
         * @description Get computed balance for an account.
         */
        get: operations["api_get_account_balance_api_accounts__account_id__balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/running-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Running Balance
         * @description Get running balance history for an account.
         */
        get: operations["api_get_running_balance_api_accounts__account_id__running_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Audit Report
         * @description Run full ledger audit and return combined report.
         *
         *     Phase 2C: Read-only integrity verification.
         *
         *     Returns:
         *         {
         *             "overall_status": "PASS" or "FAIL",
         *             "ledger_integrity": {...},
         *             "hash_verification": {...}
         *         }
         */
        get: operations["api_audit_report_api_audit_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Banks
         * @description List all known banks from uploaded statements.
         *
         *     Returns:
         *         List of unique bank names
         */
        get: operations["get_banks_api_banks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/behavior/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Behavior Summary
         * @description Get comprehensive behavioral profile.
         *
         *     Phase 3: Advanced Behavioral Intelligence Layer.
         *
         *     Returns:
         *         {
         *             "temporal_patterns": {...},
         *             "behavioral_indices": {...},
         *             "risk_signals": {...},
         *             "confidence": float (0–1),
         *             "financial_health_score": float (0–100)
         *         }
         */
        get: operations["api_behavior_summary_api_behavior_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/behavior/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Behavior Score
         * @description Get financial health score with breakdown.
         *
         *     Phase 3: Composite health score with component breakdown.
         *
         *     Returns:
         *         {
         *             "financial_health_score": float (0–100),
         *             "confidence": float (0–1),
         *             "components": {...},
         *             "summary": str
         *         }
         */
        get: operations["api_behavior_score_api_behavior_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/behavior/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Behavior Insights
         * @description Get behavioral insights and nudges.
         *
         *     Phase 3: Evidence-based insights with actionable suggestions.
         *
         *     Returns:
         *         {
         *             "insights": [...],
         *             "nudges": [...],
         *             "top_nudge": {...},
         *             "summary": str
         *         }
         */
        get: operations["api_behavior_insights_api_behavior_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Statements
         * @description Get all statements with metadata.
         */
        get: operations["get_statements_api_statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cards
         * @description Returns credit cards with their latest statement summary.
         *     Groups statements by card_last4 and bank.
         *     Returns one entry per unique card with latest statement data.
         */
        get: operations["get_cards_api_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements/{statement_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Validate Statement
         * @description Validate a statement's closing balance against computed balance.
         */
        get: operations["api_validate_statement_api_statements__statement_id__validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cashflow/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cashflow Monthly
         * @description Returns month-by-month income and expense aggregation.
         *     All monetary values in paise (INTEGER).
         */
        get: operations["get_cashflow_monthly_api_cashflow_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Dashboard Summary
         * @description Get simplified dashboard summary for MVP.
         *
         *     Returns 4 key metrics:
         *     - Net Cash Flow
         *     - Savings Rate %
         *     - EMI Ratio %
         *     - Buffer Days
         */
        get: operations["api_dashboard_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description Export transactions to CSV.
         */
        get: operations["export_csv_api_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Statement
         * @description Upload and process a PDF statement.
         */
        post: operations["upload_statement_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Detect
         * @description Detect CSV/Excel format.
         */
        post: operations["import_detect_api_import_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Execute
         * @description Execute CSV/Excel import.
         */
        post: operations["import_execute_api_import_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Investments
         * @description Get all investments with calculated returns.
         */
        get: operations["get_investments_api_investments_get"];
        put?: never;
        /**
         * Create Investment
         * @description Create a new investment.
         */
        post: operations["create_investment_api_investments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Investment
         * @description Update an investment.
         */
        put: operations["update_investment_api_investments__investment_id__put"];
        post?: never;
        /**
         * Delete Investment
         * @description Delete an investment.
         */
        delete: operations["delete_investment_api_investments__investment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loans
         * @description Get all active loans with computed summary.
         */
        get: operations["get_loans_api_loans_get"];
        put?: never;
        /**
         * Create Loan
         * @description Create a new loan record.
         */
        post: operations["create_loan_api_loans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Loan
         * @description Update loan outstanding or other fields.
         */
        put: operations["update_loan_api_loans__loan_id__put"];
        post?: never;
        /**
         * Delete Loan
         * @description Soft delete a loan.
         */
        delete: operations["delete_loan_api_loans__loan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loan_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loan Schedule
         * @description Get amortization schedule for a loan.
         */
        get: operations["get_loan_schedule_api_loans__loan_id__schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loan_id}/prepayment-simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Prepayment
         * @description Simulate impact of a prepayment.
         */
        post: operations["simulate_prepayment_api_loans__loan_id__prepayment_simulation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Managed Accounts
         * @description Get all persistently stored accounts.
         */
        get: operations["api_get_managed_accounts_api_accounts_manage_get"];
        put?: never;
        /**
         * Api Create Managed Account
         * @description Create a new persistent account.
         */
        post: operations["api_create_managed_account_api_accounts_manage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/manage/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Api Update Managed Account
         * @description Update an existing account.
         */
        put: operations["api_update_managed_account_api_accounts_manage__account_id__put"];
        post?: never;
        /**
         * Api Delete Managed Account
         * @description Soft delete an account.
         */
        delete: operations["api_delete_managed_account_api_accounts_manage__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Networth
         * @description Compute net worth from all financial data.
         *
         *     Net Worth = Assets - Liabilities
         *     Assets = account balances + investment current values
         *     Liabilities = loan outstanding + card outstanding
         */
        get: operations["get_networth_api_networth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Reconciliations
         * @description Get all reconciliations with transaction details.
         *
         *     Phase 2B: Metadata-only, no ledger mutation.
         *
         *     Args:
         *         status: Optional filter ('pending', 'confirmed', 'rejected')
         */
        get: operations["api_get_reconciliations_api_reconciliations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Pending Reconciliations
         * @description Get all pending reconciliations.
         */
        get: operations["api_get_pending_reconciliations_api_reconciliations_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Scan Reconciliations
         * @description Scan for potential transfer matches across accounts.
         *
         *     Phase 2B.1: Deterministic matching with confidence scoring.
         *
         *     Returns potential matches that can be saved as reconciliations.
         */
        get: operations["api_scan_reconciliations_api_reconciliations_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Create Reconciliation
         * @description Create a reconciliation record between two transactions.
         *
         *     Phase 2B: Metadata-only, no ledger mutation.
         *     Uses INSERT OR IGNORE for idempotency.
         */
        post: operations["api_create_reconciliation_api_reconciliations_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/batch-insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Batch Insert Reconciliations
         * @description Scan and insert all potential matches as pending reconciliations.
         *
         *     Uses INSERT OR IGNORE for idempotency - existing records are not duplicated.
         */
        post: operations["api_batch_insert_reconciliations_api_reconciliations_batch_insert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{reconciliation_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Confirm Reconciliation
         * @description Confirm a pending reconciliation.
         *
         *     Phase 2B: Updates reconciliation.status only. No ledger mutation.
         */
        post: operations["api_confirm_reconciliation_api_reconciliations__reconciliation_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{reconciliation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Reject Reconciliation
         * @description Reject a pending reconciliation.
         *
         *     Phase 2B: Updates reconciliation.status only. No ledger mutation.
         */
        post: operations["api_reject_reconciliation_api_reconciliations__reconciliation_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transactions
         * @description Get transactions as Transaction domain models.
         *
         *     FastAPI auto-serializes the Pydantic Transaction models (Money nested as paise).
         */
        get: operations["get_transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description Get overview metrics and charts.
         */
        get: operations["get_overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Get category summary and breakdown.
         */
        get: operations["get_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Get analytics data.
         */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Members
         * @description Get all members.
         *
         *     Returns list of members who have transactions.
         */
        get: operations["get_members_api_members_get"];
        put?: never;
        /**
         * Create Member
         * @description Create a new member.
         *
         *     Args:
         *         member: Member details
         *
         *     Returns:
         *         Success message and member id
         */
        post: operations["create_member_api_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountCreate
         * @description Account creation request.
         */
        AccountCreate: {
            /** Name */
            name: string;
            /** Bank */
            bank: string;
            /**
             * Account Type
             * @default savings
             */
            account_type: string;
            /** Balance Paise */
            balance_paise: number;
            /** Account Number Last4 */
            account_number_last4?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * AccountUpdate
         * @description Account update request.
         */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Bank */
            bank?: string | null;
            /** Account Type */
            account_type?: string | null;
            /** Balance Paise */
            balance_paise?: number | null;
            /** Account Number Last4 */
            account_number_last4?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Body_import_detect_api_import_detect_post */
        Body_import_detect_api_import_detect_post: {
            /** File */
            file: string;
        };
        /** Body_upload_statement_api_upload_post */
        Body_upload_statement_api_upload_post: {
            /** File */
            file: string;
            /**
             * Member
             * @default Self
             */
            member: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportExecute
         * @description Pydantic model for import execute request.
         */
        ImportExecute: {
            /** Filename */
            filename: string;
            /** Mapping */
            mapping: {
                [key: string]: unknown;
            };
            /**
             * Member
             * @default Self
             */
            member: string;
        };
        /**
         * InvestmentCreate
         * @description Investment creation request.
         */
        InvestmentCreate: {
            /** Name */
            name: string;
            /** Investment Type */
            investment_type: string;
            /** Invested Paise */
            invested_paise: number;
            /** Current Value Paise */
            current_value_paise: number;
            /** As Of Date */
            as_of_date: string;
            /** Units */
            units?: number | null;
            /** Buy Price Paise */
            buy_price_paise?: number | null;
            /** Current Price Paise */
            current_price_paise?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * InvestmentUpdate
         * @description Investment update request.
         */
        InvestmentUpdate: {
            /** Units */
            units?: number | null;
            /** Current Price Paise */
            current_price_paise?: number | null;
            /** Current Value Paise */
            current_value_paise?: number | null;
            /** As Of Date */
            as_of_date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoanCreate
         * @description Loan creation request.
         */
        LoanCreate: {
            /** Name */
            name: string;
            /** Lender */
            lender: string;
            /** Loan Type */
            loan_type: string;
            /** Principal Paise */
            principal_paise: number;
            /** Outstanding Paise */
            outstanding_paise: number;
            /** Interest Rate */
            interest_rate: number;
            /** Disbursed Date */
            disbursed_date: string;
            /** Tenure Months */
            tenure_months?: number | null;
            /** Emi Paise */
            emi_paise?: number | null;
            /** Next Emi Date */
            next_emi_date?: string | null;
            /** Gold Weight Grams */
            gold_weight_grams?: number | null;
            /** Gold Purity */
            gold_purity?: string | null;
            /**
             * Interest Type
             * @default reducing
             */
            interest_type: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoanUpdate
         * @description Loan update request.
         */
        LoanUpdate: {
            /** Outstanding Paise */
            outstanding_paise?: number | null;
            /** Interest Rate */
            interest_rate?: number | null;
            /** Tenure Months */
            tenure_months?: number | null;
            /** Emi Paise */
            emi_paise?: number | null;
            /** Next Emi Date */
            next_emi_date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MemberCreate
         * @description Member creation request.
         */
        MemberCreate: {
            /** Name */
            name: string;
            /**
             * Color
             * @default #6366F1
             */
            color: string;
        };
        /**
         * Money
         * @description Money value in paise (₹1.00 = 100 paise)
         */
        Money: {
            /** Paise */
            paise: number;
        };
        /**
         * PrepaymentRequest
         * @description Prepayment simulation request.
         */
        PrepaymentRequest: {
            /** Prepayment Paise */
            prepayment_paise: number;
            /**
             * Mode
             * @default reduce_tenure
             */
            mode: string;
        };
        /**
         * Transaction
         * @description Transaction domain entity
         */
        Transaction: {
            /** Id */
            id: number;
            /** Statement Id */
            statement_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            amount: components["schemas"]["Money"];
            /** Category */
            category: string;
            /** Member */
            member: string;
            /** Bank */
            bank?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_get_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_get_account_balance_api_accounts__account_id__balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_running_balance_api_accounts__account_id__running_balance_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_audit_report_api_audit_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_banks_api_banks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_behavior_summary_api_behavior_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_behavior_score_api_behavior_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_behavior_insights_api_behavior_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_statements_api_statements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_cards_api_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_validate_statement_api_statements__statement_id__validate_get: {
        parameters: {
            query: {
                /** @description Claimed closing balance in paise */
                claimed_balance_paise: number;
            };
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cashflow_monthly_api_cashflow_monthly_get: {
        parameters: {
            query?: {
                months?: number;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_dashboard_summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_csv_api_export_csv_get: {
        parameters: {
            query?: {
                search?: string | null;
                bank?: string | null;
                category?: string | null;
                type?: string | null;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_statement_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_statement_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_detect_api_import_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_detect_api_import_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_execute_api_import_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportExecute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investments_api_investments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_investment_api_investments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investment_api_investments__investment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investment_api_investments__investment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loans_api_loans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_loan_api_loans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_loan_api_loans__loan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_loan_api_loans__loan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loan_schedule_api_loans__loan_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_prepayment_api_loans__loan_id__prepayment_simulation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_managed_accounts_api_accounts_manage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_create_managed_account_api_accounts_manage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_update_managed_account_api_accounts_manage__account_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_delete_managed_account_api_accounts_manage__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_networth_api_networth_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_get_reconciliations_api_reconciliations_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_pending_reconciliations_api_reconciliations_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_scan_reconciliations_api_reconciliations_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_create_reconciliation_api_reconciliations_create_post: {
        parameters: {
            query: {
                /** @description Debit transaction ID */
                debit_txn_id: number;
                /** @description Credit transaction ID */
                credit_txn_id: number;
                /** @description Debit account ID */
                debit_account_id: string;
                /** @description Credit account ID */
                credit_account_id: string;
                /** @description Matched amount in rupees */
                amount: number;
                /** @description Days between transaction dates */
                date_diff_days?: number;
                /** @description Confidence score 0.0-1.0 */
                match_confidence: number;
                /** @description 'exact', 'window', 'fuzzy', or 'manual' */
                match_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_batch_insert_reconciliations_api_reconciliations_batch_insert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_confirm_reconciliation_api_reconciliations__reconciliation_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reconciliation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_reject_reconciliation_api_reconciliations__reconciliation_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reconciliation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transactions_api_transactions_get: {
        parameters: {
            query?: {
                search?: string | null;
                bank?: string | null;
                category?: string | null;
                type?: string | null;
                member?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_overview_get: {
        parameters: {
            query?: {
                exclude_transfers?: boolean;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_categories_get: {
        parameters: {
            query?: {
                exclude_transfers?: boolean;
                member?: string | null;
                drill_category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_analytics_get: {
        parameters: {
            query?: {
                exclude_transfers?: boolean;
                member?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_members_api_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_member_api_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
