from __future__ import annotations

from typing import Any

from . import agents as agents
from . import config as config
from . import context as context
from . import orchestrator as orchestrator
from . import policy as policy
from . import providers as providers
from . import tools as tools

__all__ = ["AGENT_REGISTRY", "Agent", "get_agent", "list_agents", "AI_ORCHESTRATOR_INSTANCE", "AIOrchestrator", "POLICY_ENGINE_INSTANCE", "PolicyEngine", "evaluate_policy", "TOOL_REGISTRY_INSTANCE", "ToolRegistry", "register_builtin_tools", "MODEL_ROUTER_INSTANCE", "ModelRouter", "build_context_pack"]
class Agent:
    name: str
    description: str
    authority_level: int
    enabled: bool
    def can_execute(self, run_mode: str, run_authorization_level: int) -> bool: ...
    def execute(self, context: dict[str, Any]) -> dict[str, Any]: ...
AGENT_REGISTRY: dict[str, Agent]
def get_agent(name: str) -> Agent | None: ...
def list_agents(*, enabled_only: bool = ...) -> list[dict[str, Any]]: ...
class AIOrchestrator:
    def start_run(self, *, symptom: str, mode: str = ..., capability_id: str | None = ...) -> dict[str, Any]: ...
    def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    def list_runs(self, *, limit: int = ..., status: str | None = ...) -> list[dict[str, Any]]: ...
    def execute_step(self, run_id: str, tool_name: str, arguments: dict[str, Any], *, idempotency_key: str | None = ...) -> dict[str, Any] | None: ...
    def complete_step(self, run_id: str, step_number: int, *, result: dict[str, Any] | None = ..., error: str | None = ..., evidence_id: str | None = ..., finalize: bool | None = ...) -> bool: ...
    def finalize_run(self, run_id: str) -> bool: ...
    def cancel_run(self, run_id: str) -> bool: ...
AI_ORCHESTRATOR_INSTANCE: AIOrchestrator
class PolicyEngine:
    def register_tool(self, tool_name: str, authority_level: int) -> None: ...
    def evaluate(self, *, tool_name: str, run_mode: str, run_authorization_level: int, run_id: str | None = ...) -> Any: ...
    def authorize_tool(self, run_id: str, tool_name: str) -> None: ...
    def revoke_tool(self, run_id: str, tool_name: str) -> None: ...
    def get_max_level_for_mode(self, mode: str) -> int: ...
POLICY_ENGINE_INSTANCE: PolicyEngine
def evaluate_policy(*, tool_name: str, run_mode: str, run_authorization_level: int, run_id: str | None = ...) -> Any: ...
class ToolRegistry:
    def register(self, schema: Any, handler: Any) -> None: ...
    def get(self, tool_name: str) -> Any | None: ...
    def list_tools(self, *, authority_level: int | None = ...) -> list[Any]: ...
    def invoke(self, tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]: ...
    def get_tool_schema(self, tool_name: str) -> dict[str, Any] | None: ...
TOOL_REGISTRY_INSTANCE: ToolRegistry
def register_builtin_tools(registry: ToolRegistry) -> None: ...
class ModelRouter:
    def register(self, provider: Any) -> None: ...
    def get_provider(self, name: str) -> Any | None: ...
    def list_providers(self) -> list[dict[str, Any]]: ...
    def route(self, profile: Any, *, explicit_provider: str | None = ...) -> Any: ...
    def complete(self, *, messages: list[Any], tools: list[Any] | None = ..., profile: Any | None = ..., **kwargs: Any) -> Any: ...
MODEL_ROUTER_INSTANCE: ModelRouter
def build_context_pack(*, symptom: str, capability_id: str | None = ..., run_id: str | None = ..., intent_type: str = ..., token_budget: int | None = ...) -> dict[str, Any]: ...
CONTEXT_PACK_KIND: str
