"""Canonical architecture models — Program 13.2.

These are the ONLY architectural types the Engineering Runtime may reason
about. They are produced exclusively by
:mod:`runtime.foundation.architecture.provider`, which reads the constitutional
artifacts generated by the single architecture discovery pipeline.

Key distinctions (the constitutional model established by Program 13.1):

* An **Engine** is an architectural UNIT identified by a package directory
  (``__init__.py`` is its public API) or, for small cohesive engines, a single
  file. It is the ownership root for its compute functions.
* An **EngineModule** is an implementation file INSIDE an engine. It is owned
  BY the engine and is NEVER an ownership root. ``*.py`` != Engine.
* A **Detector** is a specialised EngineModule that implements a detection
  contract.
* A **Facade** re-exports another engine (parked/legacy or namespace facade).
  It is not an engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# ---------------------------------------------------------------------------
# Leaf nodes
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ImplementationModule:
    """A non-engine implementation file that belongs to an engine."""

    id: str
    path: str
    engine: str
    node_type: str = "EngineModule"
    classes: tuple[str, ...] = ()
    functions: tuple[str, ...] = ()
    docstring: str = ""

    @property
    def name(self) -> str:
        return self.path.rsplit("/", 1)[-1]

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "path": self.path,
            "engine": self.engine,
            "node_type": self.node_type,
            "classes": list(self.classes),
            "functions": list(self.functions),
            "docstring": self.docstring,
        }


@dataclass(frozen=True, slots=True)
class Detector(ImplementationModule):
    """A Detector is an implementation module, never a standalone engine."""

    node_type: str = "Detector"


@dataclass(frozen=True, slots=True)
class Facade:
    """A façade module. Not an engine; it merely re-exports one."""

    id: str
    path: str
    status: str
    replaces: str | None = None
    import_references: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "path": self.path,
            "status": self.status,
            "replaces": self.replaces,
            "import_references": self.import_references,
        }


@dataclass(frozen=True, slots=True)
class Endpoint:
    id: str
    method: str
    path: str
    router: str
    engines: tuple[str, ...] = ()
    capabilities: tuple[str, ...] = ()

    @property
    def signature(self) -> str:
        return f"{self.method} {self.path}"

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "method": self.method,
            "path": self.path,
            "signature": self.signature,
            "router": self.router,
            "engines": list(self.engines),
            "capabilities": list(self.capabilities),
        }


@dataclass(frozen=True, slots=True)
class Router:
    id: str
    path: str
    endpoints: tuple[str, ...] = ()
    engines: tuple[str, ...] = ()

    @property
    def name(self) -> str:
        return self.path.rsplit("/", 1)[-1].removesuffix(".py")

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "path": self.path,
            "name": self.name,
            "endpoints": list(self.endpoints),
            "engines": list(self.engines),
        }


@dataclass(frozen=True, slots=True)
class Service:
    id: str
    path: str
    engines: tuple[str, ...] = ()
    routers: tuple[str, ...] = ()

    @property
    def name(self) -> str:
        return self.path.rsplit("/", 1)[-1].removesuffix(".py")

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "path": self.path,
            "name": self.name,
            "engines": list(self.engines),
            "routers": list(self.routers),
        }


@dataclass(frozen=True, slots=True)
class Repository:
    id: str
    name: str
    path: str = ""
    engines: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "path": self.path,
            "engines": list(self.engines),
        }


@dataclass(frozen=True, slots=True)
class Capability:
    id: str
    name: str
    path: str = ""
    engines: tuple[str, ...] = ()
    endpoints: tuple[str, ...] = ()
    workspaces: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "path": self.path,
            "engines": list(self.engines),
            "endpoints": list(self.endpoints),
            "workspaces": list(self.workspaces),
        }


@dataclass(frozen=True, slots=True)
class Workspace:
    id: str
    name: str
    path: str = ""
    capabilities: tuple[str, ...] = ()
    components: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "path": self.path,
            "capabilities": list(self.capabilities),
            "components": list(self.components),
        }


@dataclass(frozen=True, slots=True)
class Component:
    id: str
    name: str
    path: str = ""
    workspaces: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "path": self.path,
            "workspaces": list(self.workspaces),
        }


@dataclass(frozen=True, slots=True)
class Mapper:
    id: str
    name: str
    path: str = ""
    layer: str = "backend"

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "name": self.name, "path": self.path, "layer": self.layer}


@dataclass(frozen=True, slots=True)
class DTO:
    id: str
    name: str
    path: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "name": self.name, "path": self.path}


@dataclass(frozen=True, slots=True)
class ViewModel:
    id: str
    name: str
    path: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "name": self.name, "path": self.path}


@dataclass(frozen=True, slots=True)
class Artifact:
    id: str
    path: str
    producer: str
    owner: str
    consumers: tuple[str, ...] = ()
    verification_stage: str = ""
    pipeline: str = ""
    lifecycle: str = ""
    retention: str = ""
    regeneration_source: str = ""
    engine: str | None = None
    capability: str | None = None
    unknown_ownership: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "artifact": self.path,
            "producer": self.producer,
            "owner": self.owner,
            "consumers": list(self.consumers),
            "verification_stage": self.verification_stage,
            "pipeline": self.pipeline,
            "lifecycle": self.lifecycle,
            "retention": self.retention,
            "regeneration_source": self.regeneration_source,
            "engine": self.engine,
            "capability": self.capability,
            "unknown_ownership": self.unknown_ownership,
        }


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Engine:
    """A canonical Engine.

    ``style`` is ``package`` or ``single_file``. For package engines ``path``
    is the package DIRECTORY, and ``entry_point`` is its ``__init__.py``.
    Implementation modules are children — never engines.
    """

    id: str
    name: str
    style: str
    path: str
    entry_point: str
    implementation_modules: tuple[str, ...] = ()
    detectors: tuple[str, ...] = ()
    services: tuple[str, ...] = ()
    routers: tuple[str, ...] = ()
    repositories: tuple[str, ...] = ()
    endpoints: tuple[str, ...] = ()
    capabilities: tuple[str, ...] = ()
    tests: tuple[str, ...] = ()
    artifacts: tuple[str, ...] = ()
    migration_status: str = ""
    internal: bool = False
    evidence: dict[str, Any] = field(default_factory=dict)

    @property
    def is_package(self) -> bool:
        return self.style == "package"

    @property
    def has_router(self) -> bool:
        return bool(self.routers)

    @property
    def has_capability(self) -> bool:
        return bool(self.capabilities)

    def owns_path(self, path: str) -> bool:
        """True if ``path`` is this engine's entry point or an owned module."""
        norm = path.replace("\\", "/").rstrip("/")
        if norm == self.entry_point or norm == self.path:
            return True
        if norm in self.implementation_modules or norm in self.detectors:
            return True
        if self.is_package:
            return norm.startswith(self.path.rstrip("/") + "/")
        return False

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "style": self.style,
            "path": self.path,
            "entry_point": self.entry_point,
            "implementation_modules": list(self.implementation_modules),
            "detectors": list(self.detectors),
            "services": list(self.services),
            "routers": list(self.routers),
            "repositories": list(self.repositories),
            "endpoints": list(self.endpoints),
            "capabilities": list(self.capabilities),
            "tests": list(self.tests),
            "artifacts": list(self.artifacts),
            "migration_status": self.migration_status,
            "internal": self.internal,
            "evidence": self.evidence,
        }


# ---------------------------------------------------------------------------
# Graphs
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class GraphNode:
    id: str
    type: str
    label: str

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "type": self.type, "label": self.label}


@dataclass(frozen=True, slots=True)
class GraphEdge:
    source: str
    target: str
    relation: str
    evidence: str = ""
    attributes: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        out = {
            "from": self.source,
            "to": self.target,
            "relation": self.relation,
            "evidence": self.evidence,
        }
        out.update(self.attributes)
        return out


@dataclass(frozen=True, slots=True)
class Graph:
    kind: str
    description: str
    nodes: tuple[GraphNode, ...]
    edges: tuple[GraphEdge, ...]

    def node_ids(self) -> set[str]:
        return {n.id for n in self.nodes}

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "description": self.description,
            "node_count": len(self.nodes),
            "edge_count": len(self.edges),
            "nodes": [n.to_dict() for n in self.nodes],
            "edges": [e.to_dict() for e in self.edges],
        }


# ---------------------------------------------------------------------------
# Architecture aggregate
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Architecture:
    """The complete canonical architecture. Read-only, evidence-backed."""

    generated_at: str
    source_artifacts: tuple[str, ...]
    engines: dict[str, Engine]
    engine_modules: dict[str, ImplementationModule]
    detectors: dict[str, Detector]
    facades: dict[str, Facade]
    capabilities: dict[str, Capability]
    routers: dict[str, Router]
    endpoints: dict[str, Endpoint]
    services: dict[str, Service]
    repositories: dict[str, Repository]
    workspaces: dict[str, Workspace]
    components: dict[str, Component]
    mappers: dict[str, Mapper]
    dtos: dict[str, DTO]
    view_models: dict[str, ViewModel]
    artifacts: dict[str, Artifact]
    ownership: Graph
    execution: Graph
    dependency: Graph

    # -- lookups ----------------------------------------------------------
    def engine(self, name_or_id: str) -> Engine | None:
        if name_or_id in self.engines:
            return self.engines[name_or_id]
        for eng in self.engines.values():
            if eng.name == name_or_id:
                return eng
        return None

    def engine_for_path(self, path: str) -> Engine | None:
        """Resolve the OWNING engine of a repository path using evidence.

        Never assumes ``file == engine``: an implementation module resolves to
        its parent engine, and a package directory resolves to the engine root.
        """
        norm = (path or "").replace("\\", "/")
        if not norm:
            return None
        module = self.engine_modules.get(norm) or self.detectors.get(norm)
        if module is not None:
            return self.engines.get(module.engine)
        best: Engine | None = None
        for eng in self.engines.values():
            if eng.owns_path(norm):
                if best is None or len(eng.path) > len(best.path):
                    best = eng
        return best

    def counts(self) -> dict[str, int]:
        return {
            "engines": len(self.engines),
            "engine_modules": len(self.engine_modules),
            "detectors": len(self.detectors),
            "facades": len(self.facades),
            "capabilities": len(self.capabilities),
            "routers": len(self.routers),
            "endpoints": len(self.endpoints),
            "services": len(self.services),
            "repositories": len(self.repositories),
            "workspaces": len(self.workspaces),
            "components": len(self.components),
            "mappers": len(self.mappers),
            "dtos": len(self.dtos),
            "view_models": len(self.view_models),
            "artifacts": len(self.artifacts),
        }
