/**
 * Captured verbatim from the live `GET /api/v1/forecast` endpoint.
 *
 * Generated by seeding a temporary database and recording the real responses:
 *   - `empty_db`            — schema only, no transactions
 *   - `populated_3months_*` — three months of recorded income and expense,
 *                             at horizons 1, 6, 24 and 60
 *
 * Held as a literal rather than fetched so this suite is hermetic: it must be
 * able to fail in CI with no backend running. Regenerate with
 * `/tmp/kilo/capture_forecast_payloads.py` after changing the forecast
 * contract.
 */
interface ForecastPayload {
  cashflow_projections: {
    month: string;
    income_paise: number;
    expenses_paise: number;
    net_paise: number;
  }[];
  net_worth_projections: {
    date: string;
    projected_paise: number;
    lower_bound_paise: number;
    upper_bound_paise: number;
  }[];
  confidence_intervals: { level: number; lower_paise: number; upper_paise: number }[];
  cashflow_forecast_basis: {
    status: string;
    reason: string | null;
    model: string | null;
    history_months: number;
    projected_months: number;
    requested_horizon_months: number;
    confidence_bps: number | null;
  };
  summary: { current_net_worth_paise: number };
}

export const FORECAST_PAYLOADS: Record<string, ForecastPayload> = {
  "empty_db": {
    "cashflow_projections": [],
    "net_worth_projections": [
      {
        "date": "2026-11-03",
        "projected_paise": 903750,
        "lower_bound_paise": 903750,
        "upper_bound_paise": 903750
      },
      {
        "date": "2026-12-03",
        "projected_paise": 907515,
        "lower_bound_paise": 907515,
        "upper_bound_paise": 907515
      },
      {
        "date": "2027-01-03",
        "projected_paise": 911296,
        "lower_bound_paise": 911296,
        "upper_bound_paise": 911296
      },
      {
        "date": "2027-02-03",
        "projected_paise": 915094,
        "lower_bound_paise": 915094,
        "upper_bound_paise": 915094
      },
      {
        "date": "2027-03-03",
        "projected_paise": 918906,
        "lower_bound_paise": 918906,
        "upper_bound_paise": 918906
      },
      {
        "date": "2027-04-03",
        "projected_paise": 922735,
        "lower_bound_paise": 922735,
        "upper_bound_paise": 922735
      }
    ],
    "confidence_intervals": [],
    "cashflow_forecast_basis": {
      "status": "unavailable",
      "reason": "Cashflow forecasting needs at least 2 measured months of income and expense history; 0 month(s) recorded. No projection is reported rather than one invented from constants.",
      "model": null,
      "confidence_bps": null,
      "history_months": 0,
      "projected_months": 0,
      "requested_horizon_months": 6
    },
    "summary": {
      "current_net_worth_paise": 900000
    }
  },
  "populated_3months_h6": {
    "cashflow_projections": [
      {
        "month": "2026-10",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-11",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-12",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-01",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-02",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-03",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      }
    ],
    "net_worth_projections": [
      {
        "date": "2026-11-03",
        "projected_paise": 903750,
        "lower_bound_paise": 251042,
        "upper_bound_paise": 1556458
      },
      {
        "date": "2026-12-03",
        "projected_paise": 907515,
        "lower_bound_paise": 252088,
        "upper_bound_paise": 1562942
      },
      {
        "date": "2027-01-03",
        "projected_paise": 911296,
        "lower_bound_paise": 253138,
        "upper_bound_paise": 1569454
      },
      {
        "date": "2027-02-03",
        "projected_paise": 915094,
        "lower_bound_paise": 254193,
        "upper_bound_paise": 1575995
      },
      {
        "date": "2027-03-03",
        "projected_paise": 918906,
        "lower_bound_paise": 255252,
        "upper_bound_paise": 1582560
      },
      {
        "date": "2027-04-03",
        "projected_paise": 922735,
        "lower_bound_paise": 256316,
        "upper_bound_paise": 1589154
      }
    ],
    "confidence_intervals": [
      {
        "level": 100,
        "lower_paise": 250000,
        "upper_paise": 1550000
      }
    ],
    "cashflow_forecast_basis": {
      "status": "available",
      "reason": null,
      "model": "v1.0-weightedaverage",
      "confidence_bps": 10000,
      "history_months": 3,
      "projected_months": 6,
      "requested_horizon_months": 6
    },
    "summary": {
      "current_net_worth_paise": 900000
    }
  },
  "populated_3months_h1": {
    "cashflow_projections": [
      {
        "month": "2026-10",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      }
    ],
    "net_worth_projections": [
      {
        "date": "2026-11-03",
        "projected_paise": 903750,
        "lower_bound_paise": 251042,
        "upper_bound_paise": 1556458
      }
    ],
    "confidence_intervals": [
      {
        "level": 100,
        "lower_paise": 250000,
        "upper_paise": 1550000
      }
    ],
    "cashflow_forecast_basis": {
      "status": "available",
      "reason": null,
      "model": "v1.0-weightedaverage",
      "confidence_bps": 10000,
      "history_months": 3,
      "projected_months": 1,
      "requested_horizon_months": 1
    },
    "summary": {
      "current_net_worth_paise": 900000
    }
  },
  "populated_3months_h24": {
    "cashflow_projections": [
      {
        "month": "2026-10",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-11",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-12",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-01",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-02",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-03",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-04",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-05",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-06",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-07",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-08",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-09",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      }
    ],
    "net_worth_projections": [
      {
        "date": "2026-11-03",
        "projected_paise": 903750,
        "lower_bound_paise": 251042,
        "upper_bound_paise": 1556458
      },
      {
        "date": "2026-12-03",
        "projected_paise": 907515,
        "lower_bound_paise": 252088,
        "upper_bound_paise": 1562942
      },
      {
        "date": "2027-01-03",
        "projected_paise": 911296,
        "lower_bound_paise": 253138,
        "upper_bound_paise": 1569454
      },
      {
        "date": "2027-02-03",
        "projected_paise": 915094,
        "lower_bound_paise": 254193,
        "upper_bound_paise": 1575995
      },
      {
        "date": "2027-03-03",
        "projected_paise": 918906,
        "lower_bound_paise": 255252,
        "upper_bound_paise": 1582560
      },
      {
        "date": "2027-04-03",
        "projected_paise": 922735,
        "lower_bound_paise": 256316,
        "upper_bound_paise": 1589154
      },
      {
        "date": "2027-05-03",
        "projected_paise": 926580,
        "lower_bound_paise": 257384,
        "upper_bound_paise": 1595776
      },
      {
        "date": "2027-06-03",
        "projected_paise": 930441,
        "lower_bound_paise": 258456,
        "upper_bound_paise": 1602426
      },
      {
        "date": "2027-07-03",
        "projected_paise": 934318,
        "lower_bound_paise": 259533,
        "upper_bound_paise": 1609103
      },
      {
        "date": "2027-08-03",
        "projected_paise": 938210,
        "lower_bound_paise": 260614,
        "upper_bound_paise": 1615806
      },
      {
        "date": "2027-09-03",
        "projected_paise": 942120,
        "lower_bound_paise": 261700,
        "upper_bound_paise": 1622540
      },
      {
        "date": "2027-10-03",
        "projected_paise": 946045,
        "lower_bound_paise": 262791,
        "upper_bound_paise": 1629299
      },
      {
        "date": "2027-11-03",
        "projected_paise": 949987,
        "lower_bound_paise": 263886,
        "upper_bound_paise": 1636088
      },
      {
        "date": "2027-12-03",
        "projected_paise": 953945,
        "lower_bound_paise": 264985,
        "upper_bound_paise": 1642905
      },
      {
        "date": "2028-01-03",
        "projected_paise": 957920,
        "lower_bound_paise": 266089,
        "upper_bound_paise": 1649751
      },
      {
        "date": "2028-02-03",
        "projected_paise": 961911,
        "lower_bound_paise": 267198,
        "upper_bound_paise": 1656624
      },
      {
        "date": "2028-03-03",
        "projected_paise": 965919,
        "lower_bound_paise": 268311,
        "upper_bound_paise": 1663527
      },
      {
        "date": "2028-04-03",
        "projected_paise": 969944,
        "lower_bound_paise": 269429,
        "upper_bound_paise": 1670459
      },
      {
        "date": "2028-05-03",
        "projected_paise": 973986,
        "lower_bound_paise": 270552,
        "upper_bound_paise": 1677420
      },
      {
        "date": "2028-06-03",
        "projected_paise": 978044,
        "lower_bound_paise": 271679,
        "upper_bound_paise": 1684409
      },
      {
        "date": "2028-07-03",
        "projected_paise": 982119,
        "lower_bound_paise": 272811,
        "upper_bound_paise": 1691427
      },
      {
        "date": "2028-08-03",
        "projected_paise": 986211,
        "lower_bound_paise": 273948,
        "upper_bound_paise": 1698474
      },
      {
        "date": "2028-09-03",
        "projected_paise": 990320,
        "lower_bound_paise": 275089,
        "upper_bound_paise": 1705551
      },
      {
        "date": "2028-10-03",
        "projected_paise": 994447,
        "lower_bound_paise": 276236,
        "upper_bound_paise": 1712658
      }
    ],
    "confidence_intervals": [
      {
        "level": 100,
        "lower_paise": 250000,
        "upper_paise": 1550000
      }
    ],
    "cashflow_forecast_basis": {
      "status": "available",
      "reason": "Requested 24 months; the v1.0-weightedaverage model projects at most 12, so 12 months are reported.",
      "model": "v1.0-weightedaverage",
      "confidence_bps": 10000,
      "history_months": 3,
      "projected_months": 12,
      "requested_horizon_months": 24
    },
    "summary": {
      "current_net_worth_paise": 900000
    }
  },
  "populated_3months_h60": {
    "cashflow_projections": [
      {
        "month": "2026-10",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-11",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2026-12",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-01",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-02",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-03",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-04",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-05",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-06",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-07",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-08",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      },
      {
        "month": "2027-09",
        "income_paise": 900000,
        "expenses_paise": 250000,
        "net_paise": 650000
      }
    ],
    "net_worth_projections": [
      {
        "date": "2026-11-03",
        "projected_paise": 903750,
        "lower_bound_paise": 251042,
        "upper_bound_paise": 1556458
      },
      {
        "date": "2026-12-03",
        "projected_paise": 907515,
        "lower_bound_paise": 252088,
        "upper_bound_paise": 1562942
      },
      {
        "date": "2027-01-03",
        "projected_paise": 911296,
        "lower_bound_paise": 253138,
        "upper_bound_paise": 1569454
      },
      {
        "date": "2027-02-03",
        "projected_paise": 915094,
        "lower_bound_paise": 254193,
        "upper_bound_paise": 1575995
      },
      {
        "date": "2027-03-03",
        "projected_paise": 918906,
        "lower_bound_paise": 255252,
        "upper_bound_paise": 1582560
      },
      {
        "date": "2027-04-03",
        "projected_paise": 922735,
        "lower_bound_paise": 256316,
        "upper_bound_paise": 1589154
      },
      {
        "date": "2027-05-03",
        "projected_paise": 926580,
        "lower_bound_paise": 257384,
        "upper_bound_paise": 1595776
      },
      {
        "date": "2027-06-03",
        "projected_paise": 930441,
        "lower_bound_paise": 258456,
        "upper_bound_paise": 1602426
      },
      {
        "date": "2027-07-03",
        "projected_paise": 934318,
        "lower_bound_paise": 259533,
        "upper_bound_paise": 1609103
      },
      {
        "date": "2027-08-03",
        "projected_paise": 938210,
        "lower_bound_paise": 260614,
        "upper_bound_paise": 1615806
      },
      {
        "date": "2027-09-03",
        "projected_paise": 942120,
        "lower_bound_paise": 261700,
        "upper_bound_paise": 1622540
      },
      {
        "date": "2027-10-03",
        "projected_paise": 946045,
        "lower_bound_paise": 262791,
        "upper_bound_paise": 1629299
      },
      {
        "date": "2027-11-03",
        "projected_paise": 949987,
        "lower_bound_paise": 263886,
        "upper_bound_paise": 1636088
      },
      {
        "date": "2027-12-03",
        "projected_paise": 953945,
        "lower_bound_paise": 264985,
        "upper_bound_paise": 1642905
      },
      {
        "date": "2028-01-03",
        "projected_paise": 957920,
        "lower_bound_paise": 266089,
        "upper_bound_paise": 1649751
      },
      {
        "date": "2028-02-03",
        "projected_paise": 961911,
        "lower_bound_paise": 267198,
        "upper_bound_paise": 1656624
      },
      {
        "date": "2028-03-03",
        "projected_paise": 965919,
        "lower_bound_paise": 268311,
        "upper_bound_paise": 1663527
      },
      {
        "date": "2028-04-03",
        "projected_paise": 969944,
        "lower_bound_paise": 269429,
        "upper_bound_paise": 1670459
      },
      {
        "date": "2028-05-03",
        "projected_paise": 973986,
        "lower_bound_paise": 270552,
        "upper_bound_paise": 1677420
      },
      {
        "date": "2028-06-03",
        "projected_paise": 978044,
        "lower_bound_paise": 271679,
        "upper_bound_paise": 1684409
      },
      {
        "date": "2028-07-03",
        "projected_paise": 982119,
        "lower_bound_paise": 272811,
        "upper_bound_paise": 1691427
      },
      {
        "date": "2028-08-03",
        "projected_paise": 986211,
        "lower_bound_paise": 273948,
        "upper_bound_paise": 1698474
      },
      {
        "date": "2028-09-03",
        "projected_paise": 990320,
        "lower_bound_paise": 275089,
        "upper_bound_paise": 1705551
      },
      {
        "date": "2028-10-03",
        "projected_paise": 994447,
        "lower_bound_paise": 276236,
        "upper_bound_paise": 1712658
      },
      {
        "date": "2028-11-03",
        "projected_paise": 998590,
        "lower_bound_paise": 277387,
        "upper_bound_paise": 1719793
      },
      {
        "date": "2028-12-03",
        "projected_paise": 1002751,
        "lower_bound_paise": 278542,
        "upper_bound_paise": 1726960
      },
      {
        "date": "2029-01-03",
        "projected_paise": 1006929,
        "lower_bound_paise": 279703,
        "upper_bound_paise": 1734155
      },
      {
        "date": "2029-02-03",
        "projected_paise": 1011125,
        "lower_bound_paise": 280869,
        "upper_bound_paise": 1741381
      },
      {
        "date": "2029-03-03",
        "projected_paise": 1015338,
        "lower_bound_paise": 282039,
        "upper_bound_paise": 1748637
      },
      {
        "date": "2029-04-03",
        "projected_paise": 1019568,
        "lower_bound_paise": 283214,
        "upper_bound_paise": 1755922
      },
      {
        "date": "2029-05-03",
        "projected_paise": 1023816,
        "lower_bound_paise": 284394,
        "upper_bound_paise": 1763238
      },
      {
        "date": "2029-06-03",
        "projected_paise": 1028082,
        "lower_bound_paise": 285579,
        "upper_bound_paise": 1770585
      },
      {
        "date": "2029-07-03",
        "projected_paise": 1032366,
        "lower_bound_paise": 286769,
        "upper_bound_paise": 1777963
      },
      {
        "date": "2029-08-03",
        "projected_paise": 1036668,
        "lower_bound_paise": 287964,
        "upper_bound_paise": 1785372
      },
      {
        "date": "2029-09-03",
        "projected_paise": 1040987,
        "lower_bound_paise": 289164,
        "upper_bound_paise": 1792810
      },
      {
        "date": "2029-10-03",
        "projected_paise": 1045325,
        "lower_bound_paise": 290369,
        "upper_bound_paise": 1800281
      },
      {
        "date": "2029-11-03",
        "projected_paise": 1049680,
        "lower_bound_paise": 291578,
        "upper_bound_paise": 1807782
      },
      {
        "date": "2029-12-03",
        "projected_paise": 1054054,
        "lower_bound_paise": 292793,
        "upper_bound_paise": 1815315
      },
      {
        "date": "2030-01-03",
        "projected_paise": 1058446,
        "lower_bound_paise": 294013,
        "upper_bound_paise": 1822879
      },
      {
        "date": "2030-02-03",
        "projected_paise": 1062856,
        "lower_bound_paise": 295238,
        "upper_bound_paise": 1830474
      },
      {
        "date": "2030-03-03",
        "projected_paise": 1067284,
        "lower_bound_paise": 296468,
        "upper_bound_paise": 1838100
      },
      {
        "date": "2030-04-03",
        "projected_paise": 1071731,
        "lower_bound_paise": 297704,
        "upper_bound_paise": 1845758
      },
      {
        "date": "2030-05-03",
        "projected_paise": 1076197,
        "lower_bound_paise": 298944,
        "upper_bound_paise": 1853450
      },
      {
        "date": "2030-06-03",
        "projected_paise": 1080681,
        "lower_bound_paise": 300190,
        "upper_bound_paise": 1861172
      },
      {
        "date": "2030-07-03",
        "projected_paise": 1085184,
        "lower_bound_paise": 301440,
        "upper_bound_paise": 1868928
      },
      {
        "date": "2030-08-03",
        "projected_paise": 1089706,
        "lower_bound_paise": 302697,
        "upper_bound_paise": 1876715
      },
      {
        "date": "2030-09-03",
        "projected_paise": 1094246,
        "lower_bound_paise": 303958,
        "upper_bound_paise": 1884534
      },
      {
        "date": "2030-10-03",
        "projected_paise": 1098805,
        "lower_bound_paise": 305224,
        "upper_bound_paise": 1892386
      },
      {
        "date": "2030-11-03",
        "projected_paise": 1103384,
        "lower_bound_paise": 306496,
        "upper_bound_paise": 1900272
      },
      {
        "date": "2030-12-03",
        "projected_paise": 1107981,
        "lower_bound_paise": 307773,
        "upper_bound_paise": 1908189
      },
      {
        "date": "2031-01-03",
        "projected_paise": 1112598,
        "lower_bound_paise": 309055,
        "upper_bound_paise": 1916141
      },
      {
        "date": "2031-02-03",
        "projected_paise": 1117234,
        "lower_bound_paise": 310343,
        "upper_bound_paise": 1924125
      },
      {
        "date": "2031-03-03",
        "projected_paise": 1121889,
        "lower_bound_paise": 311636,
        "upper_bound_paise": 1932142
      },
      {
        "date": "2031-04-03",
        "projected_paise": 1126563,
        "lower_bound_paise": 312935,
        "upper_bound_paise": 1940191
      },
      {
        "date": "2031-05-03",
        "projected_paise": 1131257,
        "lower_bound_paise": 314239,
        "upper_bound_paise": 1948275
      },
      {
        "date": "2031-06-03",
        "projected_paise": 1135971,
        "lower_bound_paise": 315548,
        "upper_bound_paise": 1956394
      },
      {
        "date": "2031-07-03",
        "projected_paise": 1140704,
        "lower_bound_paise": 316863,
        "upper_bound_paise": 1964545
      },
      {
        "date": "2031-08-03",
        "projected_paise": 1145457,
        "lower_bound_paise": 318183,
        "upper_bound_paise": 1972731
      },
      {
        "date": "2031-09-03",
        "projected_paise": 1150230,
        "lower_bound_paise": 319509,
        "upper_bound_paise": 1980951
      },
      {
        "date": "2031-10-03",
        "projected_paise": 1155022,
        "lower_bound_paise": 320840,
        "upper_bound_paise": 1989204
      }
    ],
    "confidence_intervals": [
      {
        "level": 100,
        "lower_paise": 250000,
        "upper_paise": 1550000
      }
    ],
    "cashflow_forecast_basis": {
      "status": "available",
      "reason": "Requested 60 months; the v1.0-weightedaverage model projects at most 12, so 12 months are reported.",
      "model": "v1.0-weightedaverage",
      "confidence_bps": 10000,
      "history_months": 3,
      "projected_months": 12,
      "requested_horizon_months": 60
    },
    "summary": {
      "current_net_worth_paise": 900000
    }
  }
} as const;