from __future__ import annotations

from typing import Any

__all__ = [
    "build_architecture_authorities",
    "build_architecture_authority",
    "build_architecture_boundaries",
    "build_architecture_duplicates",
    "build_architecture_bypasses",
    "build_architecture_deprecations",
    "build_architecture_unmapped",
]

def build_architecture_authorities() -> dict[str, Any]: ...
def build_architecture_authority(name: str) -> dict[str, Any] | None: ...
def build_architecture_boundaries() -> dict[str, Any]: ...
def build_architecture_duplicates() -> dict[str, Any]: ...
def build_architecture_bypasses() -> dict[str, Any]: ...
def build_architecture_deprecations() -> dict[str, Any]: ...
def build_architecture_unmapped() -> dict[str, Any]: ...
