from __future__ import annotations

from typing import Any

__all__ = ["build_history_runs", "build_history_run", "build_history_compare", "build_history_baselines"]
def build_history_runs(*, page: int = ..., page_size: int = ...) -> dict[str, Any]: ...
def build_history_run(run_id: str) -> dict[str, Any] | None: ...
def build_history_compare(*, current_run_id: str, baseline: str, include_evidence: bool = ...) -> dict[str, Any] | None: ...
def build_history_baselines() -> dict[str, Any]: ...
