"""
Data Transfer Objects (DTOs)
=============================

DTOs define the API contract between backend and frontend.
All monetary fields use the _paise suffix to make units explicit.

Architecture:
- DTOs are the ONLY way to serialize domain objects to JSON
- All monetary fields must end with _paise
- Backward compatibility fields end with _rupees (temporary)
- DTOs provide validation and documentation via Pydantic
"""

from .account_dto import AccountDTO, AccountListResponse
from .accounts_dto import (
    AccountCalculationStepDTO,
    AccountDetailDTO,
    AccountEvidenceChainDTO,
    AccountEvidenceItemDTO,
    AccountInsightDTO,
    AccountsDTO,
    AccountsHistoryResponse,
    AccountsTransactionsResponse,
    AccountTypeBreakdownDTO,
    BalanceHistoryDTO,
)
from .behaviour_dto import (
    BehaviourCalculationStepDTO,
    BehaviourEvidenceChainDTO,
    BehaviourEvidenceItemDTO,
    BehaviourInsightDTO,
    BehaviourScoreDTO,
    DebtHealthDTO,
    SavingsRateDTO,
    SpendingPatternDTO,
    WellnessRadarDTO,
)
from .cashflow_dto import (
    CashflowCalculationStepDTO,
    CashflowCategoryDTO,
    CashflowCategoryResponse,
    CashflowEvidenceChainDTO,
    CashflowEvidenceItemDTO,
    CashflowInsightDTO,
    CashflowMonthlyDTO,
    CashflowMonthlyResponse,
    CashflowSummaryDTO,
    CashflowTransactionDTO,
    CashflowTransactionResponse,
    CashflowTrendDTO,
)
from .credit_cards_dto import (
    CreditCardEvidenceChainDTO,
    CreditCardEvidenceItemDTO,
    CreditCardInsightDTO,
    CreditCardsDTO,
    CreditCardsStatementResponse,
    CreditCardSummaryDTO,
    CreditCardsUtilizationResponse,
    StatementHistoryDTO,
    UtilizationDTO,
)
from .dashboard_dto import DashboardSummaryDTO, OverviewDTO
from .forecast_dto import (
    CashflowProjectionDTO,
    ConfidenceIntervalDTO,
    ForecastDTO,
    ForecastEvidenceChainDTO,
    ForecastEvidenceItemDTO,
    ForecastInsightDTO,
    ForecastNetWorthResponse,
    ForecastScenarioDTO,
    ForecastSummaryDTO,
)
from .investments_dto import (
    AssetAllocationDTO,
    HoldingDTO,
    InvestmentEvidenceChainDTO,
    InvestmentEvidenceItemDTO,
    InvestmentInsightDTO,
    InvestmentsDTO,
    InvestmentSummaryDTO,
    PerformanceDTO,
)
from .loans_dto import (
    AmortizationEntryDTO as LoanAmortizationEntryDTO,
)
from .loans_dto import (
    InterestAnalysisDTO,
    LoanEvidenceChainDTO,
    LoanEvidenceItemDTO,
    LoanInsightDTO,
    LoansDTO,
    LoanSummaryDTO,
    PaymentProgressDTO,
)
from .net_worth_dto import (
    NetWorthBreakdownItemDTO,
    NetWorthCompositionDTO,
    NetWorthDTO,
    NetWorthEvidenceChainDTO,
    NetWorthHistoricalSnapshotDTO,
    NetWorthHistoryResponse,
    NetWorthInsightDTO,
    NetWorthInsightsResponse,
    NetWorthTrendDTO,
)
from .reconciliation_dto import (
    AuditTrailEntryDTO,
    DiscrepancyDTO,
    ReconciliationDTO,
    ReconciliationEvidenceChainDTO,
    ReconciliationEvidenceItemDTO,
    ReconciliationInsightDTO,
    ReconciliationSummaryDTO,
    StatusOverviewDTO,
)
from .transaction_dto import TransactionDTO, TransactionListResponse

__all__ = [
    "AccountDTO",
    "AccountListResponse",
    "TransactionDTO",
    "TransactionListResponse",
    "DashboardSummaryDTO",
    "OverviewDTO",
    "NetWorthDTO",
    "NetWorthCompositionDTO",
    "NetWorthBreakdownItemDTO",
    "NetWorthHistoricalSnapshotDTO",
    "NetWorthTrendDTO",
    "NetWorthInsightDTO",
    "NetWorthEvidenceChainDTO",
    "NetWorthHistoryResponse",
    "NetWorthInsightsResponse",
    "CashflowSummaryDTO",
    "CashflowMonthlyDTO",
    "CashflowCategoryDTO",
    "CashflowTransactionDTO",
    "CashflowTrendDTO",
    "CashflowInsightDTO",
    "CashflowEvidenceChainDTO",
    "CashflowEvidenceItemDTO",
    "CashflowCalculationStepDTO",
    "CashflowMonthlyResponse",
    "CashflowCategoryResponse",
    "CashflowTransactionResponse",
    "AccountsDTO",
    "AccountDetailDTO",
    "AccountTypeBreakdownDTO",
    "BalanceHistoryDTO",
    "AccountInsightDTO",
    "AccountEvidenceChainDTO",
    "AccountEvidenceItemDTO",
    "AccountCalculationStepDTO",
    "AccountsHistoryResponse",
    "AccountsTransactionsResponse",
    "LoansDTO",
    "LoanSummaryDTO",
    "LoanAmortizationEntryDTO",
    "PaymentProgressDTO",
    "InterestAnalysisDTO",
    "LoanInsightDTO",
    "LoanEvidenceChainDTO",
    "LoanEvidenceItemDTO",
    "CreditCardsDTO",
    "CreditCardSummaryDTO",
    "StatementHistoryDTO",
    "UtilizationDTO",
    "CreditCardInsightDTO",
    "CreditCardEvidenceChainDTO",
    "CreditCardEvidenceItemDTO",
    "CreditCardsStatementResponse",
    "CreditCardsUtilizationResponse",
    "InvestmentsDTO",
    "InvestmentSummaryDTO",
    "HoldingDTO",
    "PerformanceDTO",
    "AssetAllocationDTO",
    "InvestmentInsightDTO",
    "InvestmentEvidenceChainDTO",
    "InvestmentEvidenceItemDTO",
    "ReconciliationDTO",
    "DiscrepancyDTO",
    "StatusOverviewDTO",
    "AuditTrailEntryDTO",
    "ReconciliationSummaryDTO",
    "ReconciliationInsightDTO",
    "ReconciliationEvidenceChainDTO",
    "ReconciliationEvidenceItemDTO",
    "BehaviourScoreDTO",
    "SpendingPatternDTO",
    "SavingsRateDTO",
    "DebtHealthDTO",
    "WellnessRadarDTO",
    "BehaviourInsightDTO",
    "BehaviourEvidenceChainDTO",
    "BehaviourEvidenceItemDTO",
    "BehaviourCalculationStepDTO",
    "ForecastDTO",
    "ForecastSummaryDTO",
    "NetWorthProjectionDTO",
    "CashflowProjectionDTO",
    "ForecastScenarioDTO",
    "ConfidenceIntervalDTO",
    "ForecastInsightDTO",
    "ForecastEvidenceChainDTO",
    "ForecastEvidenceItemDTO",
    "ForecastNetWorthResponse",
]
