from __future__ import annotations

from typing import Any

def diagnose(*, symptom: str, error_code: str | None = ..., capability_id: str | None = ...) -> dict[str, Any] | None: ...
def build_diagnostic_recommendation(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def register_signature(*args: Any, **kwargs: Any) -> Any: ...
def bump_signature_occurrence(*args: Any, **kwargs: Any) -> None: ...
