/**
 * Explanation - Complete explanation for a financial metric
 *
 * Composes evidence, sources, and calculation steps.
 * Generated by backend engines, preserved by frontend mapper.
 */

import type { Confidence } from './Confidence'
import type { CalculationStep } from './CalculationStep'
import type { Evidence } from './Evidence'
import type { SourceReference } from './SourceReference'

/**
 * Complete explanation for a financial metric
 */
export interface Explanation {
  readonly metric: string
  readonly value: number
  readonly confidence: Confidence
  readonly evidence: Evidence[]
  readonly sources: SourceReference[]
  readonly calculationSteps: CalculationStep[]
}

/**
 * Explanation for a recommendation
 */
export interface RecommendationExplanation {
  readonly recommendation: string
  readonly rationale: string
  readonly evidence: Evidence[]
  readonly sources: SourceReference[]
  readonly confidence: Confidence
  readonly impact: {
    readonly value: number
    readonly unit: 'paise' | 'bps' | 'count'
  }
}

/**
 * Explanation collection
 */
export interface ExplanationCollection {
  readonly explanations: Explanation[]
}
