#!/usr/bin/env bash
# =============================================================================
# scripts/freeze-env.sh — regenerate requirements.lock from the built env (M10)
#
# requirements.lock is a REGENERABLE SNAPSHOT of the resolved environment, NOT a
# second dependency authority. The declaration/version policy lives in root
# pyproject.toml; this lock captures the fully-resolved transitive set so CI and
# local can audit/pin the exact reproduction. Run it AFTER bootstrap or after
# any dependency bump.
#
#   Declaration (pyproject.toml) --pip install--> .venv --freeze--> requirements.lock
# =============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PY="$ROOT_DIR/.venv/bin/python"
[ -x "$PY" ] || { echo "ERROR: ./.venv not found — run scripts/bootstrap.sh first" >&2; exit 1; }

TMP="$(mktemp)"
# Drop the editable project self-install line (pip records the git origin as
# `-e git+...#egg=clarinfin_verification`); it is installed from source at
# bootstrap and must not pin a remote commit in the reproducible lock.
"$PY" -m pip freeze | grep -viE 'clarinfin' > "$TMP"
mv "$TMP" requirements.lock
echo "Wrote requirements.lock ($(wc -l < requirements.lock) pinned packages)."
echo "Provenance: generated by scripts/freeze-env.sh from the resolved .venv built from root pyproject.toml."
