"""Repository Query API — Phase 4.

A clean query interface over the canonical repository graph that consumes
RepositoryGraphService exclusively. All functions are pure Python — no AI,
no orchestration, no workflow generation.

The index is loaded from ``repo_intelligence/index.json`` (generated by
RepositoryBuilder). If the index does not exist, it can be regenerated.

Example::

    from repo_intelligence import RepositoryIndex

    idx = RepositoryIndex()
    print(idx.show_capability("reconciliation"))
    print(idx.find_owner_of_router("reconciliation"))
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from repo_intelligence.graph_service import RepositoryGraphService
from repo_intelligence.schema import GraphNode, GraphEdge, OWNERSHIP_CLASSES


class RepositoryIndex:
    """Query interface for the canonical repository index.

    Loads ``index.json`` on construction via RepositoryGraphService. The
    service provides a unified read-only interface over the graph; all
    traversal logic lives in the service layer.
    """

    def __init__(self, index_path: Path | None = None) -> None:
        if index_path is None:
            index_path = Path(__file__).parent / "index.json"
        self._index_path = index_path
        # Use RepositoryGraphService as the sole graph access layer
        self._service: RepositoryGraphService = load_graph_service(index_path)

    def _ensure_service(self) -> RepositoryGraphService:
        """Ensure the graph service is loaded."""
        return self._service

    # -----------------------------------------------------------------
    # Internal helpers using RepositoryGraphService
    # -----------------------------------------------------------------

    def _find_node(self, node_id: str) -> dict[str, Any] | None:
        """Find a node by ID, returning its dict representation."""
        node = self._ensure_service().get_node(node_id)
        if node is None:
            return None
        return node.to_dict()

    def _find_node_by_path(self, path: str) -> dict[str, Any] | None:
        """Find a node by matching its path property."""
        predicate = lambda n: n.path == path
        matching = self._ensure_service().find_nodes(predicate)
        if not matching:
            return None
        return matching[0].to_dict()

    def _outgoing_edges(self, node_id: str) -> list[dict[str, Any]]:
        """Get outgoing edges for a node as dicts."""
        edges = self._ensure_service().find_edges(node_id)[0]  # outgoing only
        return [e.to_dict() for e in edges]

    def _incoming_edges(self, node_id: str) -> list[dict[str, Any]]:
        """Get incoming edges for a node as dicts."""
        edges = self._ensure_service().find_edges(node_id)[1]  # incoming only
        return [e.to_dict() for e in edges]

    # -- Query: Capabilities -----------------------------------------------

    def list_capabilities(self) -> list[dict[str, Any]]:
        """List all capabilities in the repository."""
        nodes = self._ensure_service().get_nodes(node_type="capability")
        return [n.to_dict() for n in nodes]

    def show_capability(self, capability_id: str) -> dict[str, Any] | None:
        """Show all information about a capability.

        Returns a dict with the capability node, its engines, routers,
        services, repositories, endpoints, tests, documentation, dependencies,
        tables, and frontend consumers.
        """
        cap_node_obj = self._ensure_service().get_node(f"capability:{capability_id}")
        if cap_node_obj is None:
            return None
        cap_node = cap_node_obj.to_dict()
        cap_id = cap_node["properties"].get("id", capability_id)

        # Engines (implementers)
        engine_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "implements"
            and e["target"].startswith("module:")
        ]
        engines = [self._find_node(e["target"]) for e in engine_edges]
        engines = [e for e in engines if e is not None]

        # Routers
        router_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "implements"
            and e["target"].startswith("module:")
            and self._find_node(e["target"]) is not None
            and self._find_node(e["target"])["properties"].get("module_type") == "router"
        ]
        routers = [self._find_node(e["target"]) for e in router_edges]
        routers = [r for r in routers if r is not None]

        # Services
        service_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "implements"
            and e["target"].startswith("module:")
            and self._find_node(e["target"]) is not None
            and self._find_node(e["target"])["properties"].get("module_type") == "service"
        ]
        services = [self._find_node(e["target"]) for e in service_edges]
        services = [s for s in services if s is not None]

        # Repositories
        repo_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "implements"
            and e["target"].startswith("module:")
            and self._find_node(e["target"]) is not None
            and self._find_node(e["target"])["properties"].get("module_type") == "repository"
        ]
        repositories = [self._find_node(e["target"]) for e in repo_edges]
        repositories = [r for r in repositories if r is not None]

        # Endpoints
        endpoint_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "implements"
            and e["target"].startswith("endpoint:")
        ]
        endpoints = [self._find_node(e["target"]) for e in endpoint_edges]
        endpoints = [ep for ep in endpoints if ep is not None]

        # Tests
        test_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] in ("tests", "verifies")
        ]
        tests = []
        for edge in test_edges:
            target_node = self._find_node(edge["target"])
            if target_node:
                tests.append(target_node)
            else:
                tests.append({"id": edge["target"]})

        # Documentation
        doc_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "documents"
        ]
        documentation = [self._find_node(e["target"]) for e in doc_edges]
        documentation = [d for d in documentation if d is not None]

        # Dependencies (other capabilities)
        dep_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "depends_on"
            and e["target"].startswith("capability:")
        ]
        dependencies = [dep["target"] for dep in dep_edges]

        # Tables owned by capability
        table_edges = [
            e for e in self._outgoing_edges(cap_node["id"])
            if e["relationship"] == "owns"
            and e["target"].startswith("database_table:")
        ]
        tables = [self._find_node(e["target"]) for e in table_edges]
        tables = [t for t in tables if t is not None]

        # Frontend routes that consume this capability's endpoints
        route_edges: list[dict] = []
        for ep in endpoints:
            ep_id = ep["id"]
            consumers = self.find_frontend_consumers_of_endpoint(
                ep["properties"].get("path", "")
            )
            if consumers:
                route_edges.extend(consumers)

        return {
            "capability": cap_node,
            "engines": engines,
            "routers": routers,
            "services": services,
            "repositories": repositories,
            "endpoints": endpoints,
            "tests": tests,
            "documentation": documentation,
            "dependencies": dependencies,
            "tables": tables,
            "frontend_consumers": route_edges,
        }

    def find_owner_of_router(self, router_name: str) -> dict[str, Any] | None:
        """Find which capability owns a given router.

        ``router_name`` can be a module path fragment like
        ``src/routers/reconciliation.py`` or just ``reconciliation``.
        """
        # Try exact path match first
        if router_name.endswith(".py"):
            node = self._find_node_by_path(f"src/routers/{router_name}")
        else:
            node = self._find_node_by_path(f"src/routers/{router_name}.py")

        if node is None:
            # Try partial match
            predicate = lambda n: router_name in n["path"] and n["type"] == "module"
            matching = self._ensure_service().find_nodes(predicate)
            for m in matching:
                node = m.to_dict()
                break

        if node is None:
            return None

        # Find capabilities that implement this router (incoming implements edges)
        incoming = self._incoming_edges(node["id"])
        owners = [
            e["source"]
            for e in incoming
            if e["relationship"] == "implements"
            and e["source"].startswith("capability:")
        ]
        return {
            "router": node,
            "owners": owners,
        }

    def find_tests_for_module(self, module_path: str) -> list[dict[str, Any]]:
        """Find all tests that verify a given module.

        ``module_path`` should be relative to backend/, e.g.
        ``src/engines/loan_engine/foreclosure.py``.
        """
        module_node = self._find_node_by_path(module_path)
        if module_node is None:
            # Try with src/ prefix
            module_node = self._find_node_by_path(f"src/{module_path}")

        if module_node is None:
            return []

        # Find capabilities that implement this module
        incoming = self._incoming_edges(module_node["id"])
        test_results: list[dict[str, Any]] = []
        for edge in incoming:
            if edge["source"].startswith("capability:"):
                cap_id = edge["source"].replace("capability:", "")
                # Find tests for this capability
                cap_tests = self._find_tests_for_capability(cap_id)
                for t in cap_tests:
                    t["capability"] = cap_id
                    test_results.append(t)

        return test_results

    def _find_tests_for_capability(self, capability_id: str) -> list[dict[str, Any]]:
        """Find all test files associated with a capability."""
        cap_id = f"capability:{capability_id}"
        test_edges = [
            e for e in self._outgoing_edges(cap_id)
            if e["relationship"] == "tests"
        ]
        tests: list[dict[str, Any]] = []
        for edge in test_edges:
            target_node = self._find_node(edge["target"])
            if target_node:
                tests.append(target_node)
            else:
                tests.append({"id": edge["target"], "evidence": edge.get("evidence", "")})
        return tests

    def find_frontend_consumers_of_endpoint(self, endpoint_path: str) -> list[dict[str, Any]]:
        """Find frontend components that consume a given API endpoint.

        ``endpoint_path`` is the API path, e.g. ``/api/v1/accounts``.
        """
        results: list[dict[str, Any]] = []

        # Find all endpoint nodes matching this path
        predicate = lambda n: n.type == "endpoint" and n.properties.get("path") == endpoint_path
        matching_endpoints = self._ensure_service().find_nodes(predicate)

        for ep_obj in matching_endpoints:
            ep_id = ep_obj.id

            # Find API client functions that consume this endpoint
            consuming_edges = [
                e for e in self._incoming_edges(ep_id)
                if e["relationship"] == "consumes"
            ]

            for edge in consuming_edges:
                client_func_obj = self._find_node(edge["source"])
                if client_func_obj is None:
                    continue

                # Find components that import this API client
                importers = [
                    e for e in self._incoming_edges(edge["source"])
                    if e["relationship"] == "imports"
                ]
                for imp in importers:
                    component_obj = self._find_node(imp["source"])
                    if component_obj and component_obj["type"] in ("component", "module"):
                        results.append({
                            "component": component_obj["name"],
                            "component_path": component_obj["path"],
                            "api_function": client_func_obj["properties"].get("function_name", ""),
                            "api_client_path": client_func_obj["path"],
                            "endpoint": endpoint_path,
                            "method": ep_obj["properties"].get("method", ""),
                        })

        return results

    def find_documentation_for_capability(
        self, capability_id: str
    ) -> list[dict[str, Any]]:
        """Find documentation files that describe a capability."""
        cap_id = f"capability:{capability_id}"
        doc_edges = [
            e for e in self._outgoing_edges(cap_id)
            if e["relationship"] == "documents"
        ]
        docs = [self._find_node(e["target"]) for e in doc_edges]
        return [d for d in docs if d is not None]

    # -- Gap Queries -------------------------------------------------------

    def list_orphan_modules(self) -> list[dict[str, Any]]:
        """List modules not referenced by any capability."""
        gaps = self._get_gaps_data()
        return gaps.get("orphan_modules", [])

    def list_capabilities_with_no_documentation_evidence(self) -> list[dict[str, Any]]:
        """List capabilities with no documentation evidence."""
        gaps = self._get_gaps_data()
        return gaps.get("no_documentation_evidence", [])

    def list_endpoints_with_no_verification_evidence(self) -> list[dict[str, Any]]:
        """List endpoints with no verification evidence."""
        gaps = self._get_gaps_data()
        return gaps.get("no_verification_evidence", [])

    # Backward compatibility aliases
    list_undocumented_apis = list_capabilities_with_no_documentation_evidence  # type: ignore
    list_untested_endpoints = list_endpoints_with_no_verification_evidence  # type: ignore

    def list_missing_modules(self) -> list[str]:
        """List modules referenced by capabilities but not found on disk."""
        gaps = self._get_gaps_data()
        return gaps.get("missing_modules", [])

    def list_missing_dependencies(self) -> list[str]:
        """List capability dependencies that don't resolve to a known capability."""
        gaps = self._get_gaps_data()
        return gaps.get("missing_dependencies", [])

    def _get_gaps_data(self) -> Dict[str, Any]:
        """Return gap data from the underlying graph service."""
        service = self._ensure_service()
        return service.get_gaps() or {}  # Ensure dict is returned

    # -- Semantic Ownership Queries ----------------------------------------

    def list_nodes_by_ownership(self, ownership: str) -> list[dict[str, Any]]:
        """Return all nodes classified with the given ownership category."""
        if ownership not in OWNERSHIP_CLASSES:
            raise ValueError(f"Invalid ownership: {ownership}. Must be one of {OWNERSHIP_CLASSES}")

        predicate = lambda n: n.ownership == ownership
        nodes = self._ensure_service().find_nodes(predicate)
        return [n.to_dict() for n in nodes]

    def list_modules_with_unknown_ownership(self) -> list[dict[str, Any]]:
        """List modules where ownership could not be determined."""
        return self.list_nodes_by_ownership("unknown")

    # -- Phase Evidence Queries --------------------------------------------

    def list_phases_for_capability(self, capability_id: str) -> list[dict[str, Any]] | None:
        """Return the phase breakdown for a capability (if available)."""
        capability_node = self._find_node(f"capability:{capability_id}")
        if not capability_node:
            return None
        return capability_node.get("properties", {}).get("phases", [])

    def capabilities_without_verification_evidence(self) -> list[dict[str, Any]]:
        """Find capabilities that have no verification evidence attached."""
        verified_cap_ids: set[str] = set()
        all_edges = [e.to_dict() for e in self._ensure_service().find_edges("any")[0] + self._ensure_service().find_edges("any")[1]]  # rough approximation
        # Better: use direct graph access through service
        service = self._ensure_service()
        # Get all edges
        edges_list = []
        for node in service.get_nodes():
            out_edges = service.find_edges(node.id)[0]
            for e in out_edges:
                edges_list.append(e.to_dict())
            inc_edges = service.find_edges(node.id)[1]
            for e in inc_edges:
                edges_list.append(e.to_dict())

        for e in edges_list:
            if e.get("relationship") == "verifies" and e.get("source").startswith("capability:"):
                verified_cap_ids.add(e["source"])

        result = []
        for node in service.get_nodes(node_type="capability"):
            nid = node.id
            if nid not in verified_cap_ids:
                result.append(node.to_dict())
        return result

    def verify_evidence_for_endpoint(self, endpoint_id: str) -> dict[str, Any] | None:
        """Return evidence details for an endpoint (which capability verifies it)."""
        service = self._ensure_service()

        # Find all edges first
        all_edges: list[GraphEdge] = []
        for node in service.get_nodes():
            out_edges = service.find_edges(node.id)[0]
            all_edges.extend(out_edges)
            inc_edges = service.find_edges(node.id)[1]
            all_edges.extend(inc_edges)

        edge = next((e for e in all_edges if e.target == endpoint_id and e.relationship == "verifies"), None)
        if not edge:
            return {"endpoint_id": endpoint_id, "verified_by": None, "evidence": ""}

        cap_node = service.get_node(edge.source)
        return {
            "endpoint_id": endpoint_id,
            "verified_by": edge.source,
            "capability_name": cap_node.name if cap_node else "",
            "evidence": edge.evidence or "",
        }

    # -- Semantic Query Improvements ---------------------------------------

    def why(self, path: str) -> Dict[str, Any]:
        """Explain all relationships involving a given node/file path."""
        node = self._find_node_by_path(path)
        if not node:
            return {"error": f"No node found at path: {path}"}

        node_id = node["id"]
        incoming = self._incoming_edges(node_id)
        outgoing = self._outgoing_edges(node_id)

        return {
            "node": node,
            "incoming_edges": [
                {"source": e["source"], "relationship": e["relationship"], "evidence": e.get("evidence", "")}
                for e in sorted(incoming, key=lambda x: x["source"])
            ],
            "outgoing_edges": [
                {"target": e["target"], "relationship": e["relationship"], "evidence": e.get("evidence", "")}
                for e in sorted(outgoing, key=lambda x: x["target"])
            ],
        }

    def impact(self, path: str, max_depth: int = 8) -> Dict[str, Any]:
        """Compute impact of changes to a file using ImpactAnalyzer."""
        from repo_intelligence.impact import compute_impact  # avoid circular import
        return compute_impact(path, max_depth=max_depth)

    def trace(self, node_id: str, max_depth: int = 6) -> List[List[Dict[str, Any]]]:
        """Return all paths starting from a node up to max_depth.

        Uses BFS to enumerate simple paths from the given node identifier.
        Each path is a list of node dictionaries.
        """
        start_node_obj = self._ensure_service().get_node(node_id)
        if start_node_obj is None:
            return []

        start_node = start_node_obj.to_dict()
        results: List[List[Dict[str, Any]]] = []
        stack = [(start_node["id"], [start_node])]  # (current_id, path_of_dicts)

        while stack:
            current_id, path = stack.pop()
            if len(path) - 1 > max_depth:
                continue
            if len(path) > 1:  # Record paths of length >= 2
                results.append(path)

            # Find connected neighbors (both directions)
            visited_in_path = {n["id"] for n in path}
            successors = self._ensure_service().successors(current_id)
            predecessors = self._ensure_service().predecessors(current_id)
            all_neighbors = set(successors) | set(predecessors)

            for neighbor_id in sorted(all_neighbors):
                if neighbor_id not in visited_in_path:
                    neighbor_node = self._ensure_service().get_node(neighbor_id)
                    if neighbor_node:
                        new_path = path + [neighbor_node.to_dict()]
                        stack.append((neighbor_id, new_path))

        return results

    def health(self) -> Dict[str, Any]:
        """Get comprehensive repository health metrics."""
        from repo_intelligence.metrics import calculate_metrics as calc_metrics
        from repo_intelligence.graph_service import load_graph_service

        try:
            service = load_graph_service(self._index_path)
            metrics = calc_metrics(service)
            return metrics
        except Exception as e:
            return {"error": f"Could not compute health metrics: {str(e)}"}

    def search(self, text: str) -> Dict[str, Any]:
        """Search across multiple entity types for matching text."""
        text_lower = text.lower()
        results: Dict[str, List[Dict[str, Any]]] = {}

        def should_match(n: GraphNode) -> bool:
            name = n.name.lower()
            path = n.path.lower()
            props_lower = {str(k).lower(): str(v).lower() for k, v in n.properties.items()}
            return text_lower in name or text_lower in path or any(text_lower in v for v in props_lower.values())

        predicate = should_match
        nodes = self._ensure_service().find_nodes(predicate)

        for node in nodes:
            node_type = node.type
            results.setdefault(node_type, []).append(node.to_dict())

        return results


def load_graph_service(index_path: Path) -> RepositoryGraphService:
    """Convenience function to load a RepositoryGraphService from index.

    Args:
        index_path: Path to index.json.

    Returns:
        A RepositoryGraphService instance.
    """
    from repo_intelligence.graph_service import load_graph_service as _load_service
    return _load_service(index_path)