/**
 * Tests for EmptyExplanation component
 */

import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import { EmptyExplanation } from '@/components/explainability/components/EmptyExplanation'

describe('EmptyExplanation', () => {
  it('renders default title', () => {
    render(<EmptyExplanation />)
    expect(screen.getByText('No Explanation Available')).toBeInTheDocument()
  })

  it('renders custom title', () => {
    render(<EmptyExplanation title="Custom Title" />)
    expect(screen.getByText('Custom Title')).toBeInTheDocument()
  })

  it('renders default description', () => {
    render(<EmptyExplanation />)
    expect(
      screen.getByText(
        'This metric does not have an explanation yet. Explanations are generated by the backend for explainable capabilities.',
      ),
    ).toBeInTheDocument()
  })

  it('renders custom description', () => {
    render(<EmptyExplanation description="Custom description" />)
    expect(screen.getByText('Custom description')).toBeInTheDocument()
  })
})